### ISSUE TITLE
wfw is not working on mac os x, python 2.7

### ISSUE THREAD

**Issue by ipstone** [kvch/wfw#2]
Hello,

I have pip installed wfw; but after setting up .wfwrc; running wfw / trying different commands, it only returned simple error messages, without details.

For example:
```
$ wfw show
You have no local tree
```

Is it known that wfw is having these issues? Thanks

Isaac

**Comment by kvch** [comment]
Have you called `wfw fetch`? Fetch retrieves data from the server.

You are right, the error message is quite cryptic. I will change the error message to a clearer one.

**Comment by ipstone** [comment]
Thank you, Noémi. ``` wfw fetch ``` solves it! - Probably it can be added to the 'README' for new users.

Isaac
